### PR TITLE
fix: throwing error if running tests without .env.test

### LINKED ISSUE #731: Running `npm run test` will wipe the local DB
We shouldn't risk wiping the database when testing env is not correctly configured.

In my case, i have `.env` file, but not configured the `.env.test` file

CC @fabis94 : i am thinking either commit the `.env.test` in the repo, or fail the test if there is no such file. But running tests on the DB configured in .env should never happen. What do you think?

### PR DESCRIPTION
**Pull request by fabis94**
closes #731

### CODE REVIEW

File: packages/server/bootstrap.js [hunk 1]
```diff
@@ -14,7 +14,14 @@ const appRoot = require('app-root-path')
...
 // (appRoot necessary, cause env files aren't loaded through require() calls)
 if (isTestEnv()) {
-  dotenv.config({ path: `${appRoot}/.env.test` })
+  const { error } = dotenv.config({ path: `${appRoot}/.env.test` })
+  if (error) {
+    const e = new Error(
+      'Attempting to run tests without an .env.test file properly set up! Check readme!'
+    )
+    console.error(e)
+    process.exit(1)
```
Comment (fabis94) [inline packages/server/bootstrap.js:23]: Exiting directly not throwing, so that the error doesn't get caught by yargs and reported as something else (happened to me with an old node_modules)

**Review by cristi8 — APPROVED** [review]

**Review by gjedlicska — APPROVED** [review]
