### PR TITLE
Dim/minor fixes apr

### LINKED ISSUE #665: Comments Permissions UI & Frontend Subs Fixes
Marking a comment read without a logged in user throws permission error

### PR DESCRIPTION
**Pull request by didimitrie**
Should fix #665 & alleviate massively #666 :)

### CODE REVIEW

File: packages/frontend/src/main/pages/stream/TheStream.vue [hunk 1]
```diff
@@ -57,7 +57,10 @@ export default {
       }
     },
     user: {
-      query: MainUserDataQuery
+      query: MainUserDataQuery,
+      skip() {
```
Comment (didimitrie) [inline packages/frontend/src/main/pages/stream/TheStream.vue:61]: these _other_ missing skips were turning the console red for non-loggedin users cc @fabis94
